services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1.23-bookworm
    volumes:
      - ..:/workspaces/keycape:cached
    working_dir: /workspaces/keycape
    network_mode: service:db
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - keycape-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgresh
      POSTGRES_USER: postgresh
      POSTGRES_DB: keycape
volumes:
  keycape-data:
